In [1]:
import numpy as np
import pandas as pd


In [2]:
import sklearn

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from tensorflow import keras
from keras.models import Sequential

In [5]:
from keras.layers import Conv2D, Dense, BatchNormalization, Flatten, Activation, LayerNormalization, Reshape
from keras.optimizers import Adam


In [6]:
df = pd.read_csv('./sudoku.csv')


In [7]:
df

quizzes  \
0       0043002090050090010700600430060020871900074000...   
1       0401000501070039605200080000000000170009068008...   
2       6001203840084590720000060050002640300700800069...   
3       4972000001004000050000160986203000403009000000...   
4       0059103080094030600275001000300002010008200070...   
...                                                   ...   
999995  3000280000290000300054001077402030980086070031...   
999996  0030006000040860057000009409350407208067200502...   
999997  0003508200618040300500090000700600029030070100...   
999998  0702006900030400010000650205600300000947005800...   
999999  3004016201000804000050208300578000000007005030...   

                                                solutions  
0       8643712593258497619712658434361925871986574322...  
1       3461792581875239645296483719658324174729168358...  
2       6951273841384596727248369158512647392739815469...  
3       4972583161864397252537164986293815473759641828...  
4       4659123781894735623275681497386452919548216372...  
...                                                   ...  
999995  3175289464291768356854391277462135989586472131...  
999996  5234976811942863757685139429356417288167294532...  
999997  7493568212618745393582197468749613529235876146...  
999998  4752816936239478511893657245628341793947165828...  
999999  3984716251263854797456298316578139429147625838...  

[1000000 rows x 2 columns]

In [8]:
X = np.array(df.quizzes.map(lambda x: list(map(int, x))).to_list())


In [9]:
X

array([[0, 0, 4, ..., 3, 0, 0],
       [0, 4, 0, ..., 1, 0, 0],
       [6, 0, 0, ..., 1, 9, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 7, 0, ..., 0, 0, 7],
       [3, 0, 0, ..., 0, 9, 0]])

In [10]:
Y = np.array(df.solutions.map(lambda x: list(map(int, x))).to_list())


In [11]:
Y


array([[8, 6, 4, ..., 3, 7, 8],
       [3, 4, 6, ..., 1, 8, 6],
       [6, 9, 5, ..., 1, 9, 7],
       ...,
       [7, 4, 9, ..., 1, 9, 3],
       [4, 7, 5, ..., 3, 1, 7],
       [3, 9, 8, ..., 3, 9, 8]])

In [12]:
X = X.reshape(-1, 9, 9, 1)


In [13]:
X

array([[[[0],
         [0],
         [4],
         ...,
         [2],
         [0],
         [9]],

        [[0],
         [0],
         [5],
         ...,
         [0],
         [0],
         [1]],

        [[0],
         [7],
         [0],
         ...,
         [0],
         [4],
         [3]],

        ...,

        [[6],
         [0],
         [0],
         ...,
         [1],
         [0],
         [5]],

        [[0],
         [0],
         [3],
         ...,
         [6],
         [9],
         [0]],

        [[0],
         [4],
         [2],
         ...,
         [3],
         [0],
         [0]]],


       [[[0],
         [4],
         [0],
         ...,
         [0],
         [5],
         [0]],

        [[1],
         [0],
         [7],
         ...,
         [9],
         [6],
         [0]],

        [[5],
         [2],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [9],
         [0],
         ...,
         [5],


In [14]:
Y = Y.reshape(-1, 9, 9) - 1



In [15]:
Y

array([[[7, 5, 3, ..., 1, 4, 8],
        [2, 1, 4, ..., 6, 5, 0],
        [8, 6, 0, ..., 7, 3, 2],
        ...,
        [5, 7, 8, ..., 0, 1, 4],
        [6, 0, 2, ..., 5, 8, 3],
        [4, 3, 1, ..., 2, 6, 7]],

       [[2, 3, 5, ..., 1, 4, 7],
        [0, 7, 6, ..., 8, 5, 3],
        [4, 1, 8, ..., 2, 6, 0],
        ...,
        [6, 8, 7, ..., 4, 3, 2],
        [5, 2, 0, ..., 6, 8, 1],
        [1, 4, 3, ..., 0, 7, 5]],

       [[5, 8, 4, ..., 2, 7, 3],
        [0, 2, 7, ..., 5, 6, 1],
        [6, 1, 3, ..., 8, 0, 4],
        ...,
        [2, 0, 6, ..., 3, 4, 7],
        [3, 7, 8, ..., 1, 5, 2],
        [4, 5, 1, ..., 0, 8, 6]],

       ...,

       [[6, 3, 8, ..., 7, 1, 0],
        [1, 5, 0, ..., 4, 2, 8],
        [2, 4, 7, ..., 6, 3, 5],
        ...,
        [3, 8, 6, ..., 1, 5, 4],
        [0, 2, 1, ..., 3, 6, 7],
        [4, 7, 5, ..., 0, 8, 2]],

       [[3, 6, 4, ..., 5, 8, 2],
        [5, 1, 2, ..., 7, 4, 0],
        [0, 7, 8, ..., 6, 1, 3],
        ...,
        [6, 2, 5, ..., 

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)


In [17]:
x_train

array([[[[5],
         [0],
         [9],
         ...,
         [8],
         [3],
         [0]],

        [[6],
         [0],
         [0],
         ...,
         [4],
         [0],
         [0]],

        [[0],
         [3],
         [0],
         ...,
         [0],
         [1],
         [0]],

        ...,

        [[8],
         [0],
         [2],
         ...,
         [0],
         [0],
         [0]],

        [[3],
         [1],
         [0],
         ...,
         [0],
         [5],
         [0]],

        [[0],
         [5],
         [0],
         ...,
         [0],
         [7],
         [0]]],


       [[[0],
         [2],
         [1],
         ...,
         [8],
         [0],
         [0]],

        [[0],
         [3],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[4],
         [0],
         [5],
         ...,
         [0],
         [0],
         [7]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [5],


In [18]:
x_train

array([[[[5],
         [0],
         [9],
         ...,
         [8],
         [3],
         [0]],

        [[6],
         [0],
         [0],
         ...,
         [4],
         [0],
         [0]],

        [[0],
         [3],
         [0],
         ...,
         [0],
         [1],
         [0]],

        ...,

        [[8],
         [0],
         [2],
         ...,
         [0],
         [0],
         [0]],

        [[3],
         [1],
         [0],
         ...,
         [0],
         [5],
         [0]],

        [[0],
         [5],
         [0],
         ...,
         [0],
         [7],
         [0]]],


       [[[0],
         [2],
         [1],
         ...,
         [8],
         [0],
         [0]],

        [[0],
         [3],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[4],
         [0],
         [5],
         ...,
         [0],
         [0],
         [7]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [5],


In [19]:
x_test

array([[[[0],
         [0],
         [5],
         ...,
         [0],
         [8],
         [7]],

        [[0],
         [0],
         [6],
         ...,
         [2],
         [0],
         [3]],

        [[0],
         [1],
         [0],
         ...,
         [0],
         [5],
         [0]],

        ...,

        [[0],
         [6],
         [7],
         ...,
         [9],
         [0],
         [0]],

        [[0],
         [3],
         [0],
         ...,
         [4],
         [0],
         [0]],

        [[0],
         [0],
         [2],
         ...,
         [0],
         [0],
         [6]]],


       [[[2],
         [6],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[8],
         [0],
         [9],
         ...,
         [3],
         [0],
         [6]],

        [[0],
         [4],
         [7],
         ...,
         [0],
         [1],
         [0]],

        ...,

        [[1],
         [0],
         [0],
         ...,
         [0],


In [20]:
model = Sequential()


In [21]:
model.add(Conv2D(128, 3, activation='relu', padding='same', input_shape = (9, 9, 1)))


In [22]:
model.add(BatchNormalization())


In [23]:
model.add(Conv2D(128, 3, activation='relu', padding='same'))


In [24]:
model.add(BatchNormalization())


In [25]:
model.add(Conv2D(256, 3, activation='relu', padding='same'))


In [26]:
model.add(BatchNormalization())


In [27]:
model.add(Conv2D(256, 3, activation='relu', padding='same'))


In [28]:
model.add(BatchNormalization())


In [29]:
model.add(Conv2D(512, 3, activation='relu', padding='same'))


In [30]:
model.add(BatchNormalization())


In [31]:
model.add(Conv2D(512, 3, activation='relu', padding='same'))


In [32]:
model.add(BatchNormalization())


In [33]:
model.add(Conv2D(1024, 3, activation='relu', padding='same'))


In [34]:
model.add(BatchNormalization())


In [35]:
model.add(Conv2D(9, 3, activation='relu', padding='same'))


In [36]:
model.add(Flatten())


In [37]:
model.add(Dense(512))


In [38]:
model.add(Dense(81*9))


In [39]:
model.add(LayerNormalization(axis=-1))


In [40]:
model.add(Reshape((9, 9, 9)))


In [41]:
model.add(Activation('softmax'))


In [42]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])


In [43]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 9, 9, 128)         1280      
                                                                 
 batch_normalization (Batch  (None, 9, 9, 128)         512       
 Normalization)                                                  
                                                                 
 conv2d_1 (Conv2D)           (None, 9, 9, 128)         147584    
                                                                 
 batch_normalization_1 (Bat  (None, 9, 9, 128)         512       
 chNormalization)                                                
                                                                 
 conv2d_2 (Conv2D)           (None, 9, 9, 256)         295168    
                                                                 
 batch_normalization_2 (Bat  (None, 9, 9, 256)         1

In [ ]:
model.fit(x_train, y_train, batch_size=64, epochs=10, validation_data=(x_test, y_test))


Epoch 1/10


  208/12500 [..............................] - ETA: 7:17:42 - loss: 2.1935 - accuracy: 0.1318